### ISSUE TITLE
Using inside a login and register form

### ISSUE THREAD

**Issue by smartmeter** [alexandrepigeot/ReCaptchaForASP#1]
Hi, can you please include a sample to the login and register form.

It doesnt show where to put my secret key etc.

thanks

**Comment by alexandrepigeot** [comment]
Hi @smartmeter ,
Thanks for you interest.
I have just put together a small sample project. If you don't mind, could you please open it in Visual Studio and see if the explanations are clear to you? Open up "Default.cshtml" and read through commented area!

**PS! I have updated to version 2.0.3 on Nuget. Version 2.0.2 is broken, you have to use the code on GitHub until the Nuget gets published!**

[ReCaptchaSample.zip](https://github.com/alexandrepigeot/ReCaptchaForASP/files/398008/ReCaptchaSample.zip)

**Comment by smartmeter** [comment]
Awesome, testing will let you know shortly.

**Comment by alexandrepigeot** [comment]
I'm guessing this went well
